version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules
      - /home/david/frontend:/home/node/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/node/app/node_modules
      - /home/david/frontend:/home/node/app
    command: ["npm", "run", "test"]
